// Single source of truth for Content Security Policy
// Auto-generated by scripts/generate-security-headers.mjs - DO NOT EDIT MANUALLY
// Hash is for the inline application/ld+json script in index.html
// Computed as base64(sha256(bytes between <script type="application/ld+json"> and </script>))
export const CSP_JSON_LD_HASH = "sha256-guXkx/hRNTkG4ebmtlNBhEAaYW1hUdJ/KGbctVtwzbM=";

export const CSP_POLICY_CORE =
  `default-src 'self'; base-uri 'self'; object-src 'none'; script-src 'self' 'sha256-guXkx/hRNTkG4ebmtlNBhEAaYW1hUdJ/KGbctVtwzbM='; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https://avatars.githubusercontent.com; connect-src 'self'; media-src 'self'; worker-src 'self' blob:; form-action 'self' mailto: https://wa.me; upgrade-insecure-requests`;

export const CSP_POLICY_WITH_FRAME = `${CSP_POLICY_CORE.replace("object-src 'none';", "object-src 'none'; frame-ancestors 'none';")}`;

// For index.html meta tag (allows same as core)
export const CSP_META = CSP_POLICY_CORE;

// For hosting headers (adds frame-ancestors)
export const CSP_HEADER = `default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; script-src 'self' 'sha256-guXkx/hRNTkG4ebmtlNBhEAaYW1hUdJ/KGbctVtwzbM='; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https://avatars.githubusercontent.com; connect-src 'self'; media-src 'self'; worker-src 'self' blob:; form-action 'self' mailto: https://wa.me; upgrade-insecure-requests`;
